server:
  port: 81


spring:
  application:
    name: msa-service-coffee-client

  cloud:
    config:
      discovery:
        enabled: true
        service-id: 'msa-architecture-server-config' #update -> curl -X POST http://localhost:8081/actuator/refresh

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP}:9091/eureka/
      #defaultZone: http://localhost:9091/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    instance-id:

logging:
  path: logs
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.minji.msa.zuul.system: DEBUG
    com.minji.msa.zuul.springboot: DEBUG